# Generated by Django 6.0.4 on 2026-04-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0002_category_img_product_img_product_is_best_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, to='dmep.category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(blank=True, to='dmep.product'),
        ),
    ]
